
replicaCount: 2
image:
  repository: hub.hengkangit.com:6337/hk_docker/basicdata
  tag: 201901080756-prod
  pullPolicy: IfNotPresent
  dockerRegistry: registry-docker-secret-hengkangit
service:
  name: basicdata
  type: ClusterIP
  environment: Uat
  externalPort: 5000
  internalPort: 5000
  rpcExterPort: 30001
  rpcInterPort: 30001
  restartPolicy: Always
  HealthProbes: true
  HealthPath: "/health/check"
  HealthProbesLivenessTimeout: 60          
  HealthProbesReadinessTimeout: 30      
  HealthProbeLivenessFailureThreshold: 10
## Persist data to a persistent volume
persistence:
  enabled: true
  storageClass: "hk-nfs-storage-prod"
  accessMode: ReadWriteOnce
  size: 1Gi

ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts: [
    "test-basicdata.hengkangit.com"
  ]
  annotations:
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
resources:
  requests:
    memory: 300Mi
    cpu: 300m
  limits:
    memory: 1012Mi
    cpu: 500m

nodeSelector: 
  deploy-env: uat
  