apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      release: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1      
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.image.dockerRegistry }} 
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ .Release.Name }}
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
{{- if .Values.service.dbPasswd }}
        env:
        - name: MYSQL_ROOT_PASSWORD 
          value: {{ .Values.service.dbPasswd }}
{{- end }}   
{{- if .Values.service.HealthProbes }}
        livenessProbe:
          httpGet:
            path: "{{ .Values.service.HealthPath }}"
            port: "{{ .Values.service.internalPort }}-http"
          initialDelaySeconds: {{ .Values.service.HealthProbesLivenessTimeout }}
          timeoutSeconds: 15  
          periodSeconds: 10
          failureThreshold: {{ .Values.service.HealthProbeLivenessFailureThreshold }}
        readinessProbe:
          httpGet:
            path: "{{ .Values.service.HealthPath }}"
            port: "{{ .Values.service.internalPort }}-http"
          timeoutSeconds: 15
          periodSeconds: 10
          initialDelaySeconds: {{ .Values.service.HealthProbesReadinessTimeout }}
{{- end }}   
        volumeMounts:
        - mountPath: /app/zentaopms
          name: app-zentao
          subPath: zentaopms
        - mountPath: /var/lib/mysql
          name: app-zentao
          subPath: mysql
        {{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: "{{ .Values.service.internalPort }}-http"
      volumes:
      - name: app-zentao
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc-zendao
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
