{{- $serviceName := .Release.Name -}}
{{- $servicePort := .Values.service.externalPort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "traefik-ingress-{{ .Release.Name }}"
  annotations:
    kubernetes.io/ingress.class: traefik
  labels:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
    {{- end -}}

