{{- if .Values.ingress.enabled }}
{{- $serviceName := .Release.Name -}}
{{- $servicePort := .Values.service.externalPort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "traefik-ingress-{{ .Release.Name }}"
  labels:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
spec:
  rules:
  {{- if .Values.ingress.hostName }}
  - host: {{ .Values.ingress.hostName }}
    http:
  {{- else }}
  - http:
  {{- end }}
      paths:
        - path: {{ default "/" .path }}
          backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
{{- if .Values.ingress.tls }}
  tls:
  - hosts:
    {{- if  .Values.ingress.hostName }}
    - {{ .Values.ingress.hostName }}
    secretName: {{  .Values.ingress.tlsSecret }}
    {{- else}}
    - secretName: {{  .Values.ingress.tlsSecret }}
    {{- end }}
{{- end }}
{{- end }}