kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-pvc-zendao
  labels:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: "{{ .Values.persistence.zentaoSize }}"
  storageClassName: "{{ .Values.persistence.storageClass }}"